# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oQHx5lyvvUAobz0aLT7cAQ3LLDYPgvpv
"""

from google.colab import files
import pandas as pd

uploaded = files.upload()

mat = pd.read_csv("student-mat.csv", sep=";")
por = pd.read_csv("student-por.csv", sep=";")

print("Matemáticas:", mat.shape)
print("Portugués:", por.shape)

columnas_comunes = set(mat.columns).intersection(
    set(por.columns)
)

print("Columnas comunes:", len(columnas_comunes))
print(sorted(columnas_comunes))

columnas_id = [
    "school", "sex", "age", "address", "famsize",
    "Pstatus", "Medu", "Fedu", "Mjob", "Fjob",
    "reason", "guardian", "traveltime",
    "studytime", "failures"
]

mat["student_key"] = mat[columnas_id].astype(str).agg("_".join, axis=1)
por["student_key"] = por[columnas_id].astype(str).agg("_".join, axis=1)

print("Coincidencias:",
      len(set(mat["student_key"]) & set(por["student_key"])))

mat_unicos = mat.drop_duplicates("student_key")
por_unicos = por.drop_duplicates("student_key")

cruce = pd.merge(
    mat_unicos,
    por_unicos,
    on="student_key",
    suffixes=("_mat", "_por"),
    how="inner"
)

print("Base cruzada:", cruce.shape)

cruce.head()