# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1l37lVSv3xdwHZkqiNC3A1Kxd1swHe6cq
"""

from google.colab import files

uploaded = files.upload()

import pandas as pd

mat = pd.read_csv("student-mat (3).csv", sep=";")
por = pd.read_csv("student-por (3).csv", sep=";")

print("COLUMNAS MATEMÁTICAS")
print(mat.columns.tolist())

print("\nCOLUMNAS PORTUGUÉS")
print(por.columns.tolist())

print("COLUMNAS MATEMÁTICAS")
print(mat.columns.tolist())

print("\nCOLUMNAS PORTUGUÉS")
print(por.columns.tolist())

print("COLUMNAS MATEMÁTICAS")
print(mat.columns.tolist())

print("\nCOLUMNAS PORTUGUÉS")
print(por.columns.tolist())

columnas_mat = set(mat.columns)
columnas_por = set(por.columns)

columnas_comunes = columnas_mat.intersection(columnas_por)

print("Número de columnas comunes:", len(columnas_comunes))
print("\nColumnas comunes:")
print(sorted(columnas_comunes))

columnas_id = [
    "school",
    "sex",
    "age",
    "address",
    "famsize",
    "Pstatus",
    "Medu",
    "Fedu",
    "Mjob",
    "Fjob",
    "reason",
    "guardian"
]

print("Duplicados en Matemáticas:")
print(mat[columnas_id].duplicated().sum())

print("\nDuplicados en Portugués:")
print(por[columnas_id].duplicated().sum())

columnas_id = [
    "school",
    "sex",
    "age",
    "address",
    "famsize",
    "Pstatus",
    "Medu",
    "Fedu",
    "Mjob",
    "Fjob",
    "reason",
    "guardian",
    "traveltime",
    "studytime",
    "failures"
]

print("Duplicados en Matemáticas:")
print(mat[columnas_id].duplicated().sum())

print("\nDuplicados en Portugués:")
print(por[columnas_id].duplicated().sum())

mat["student_key"] = mat[columnas_id].astype(str).agg("_".join, axis=1)

por["student_key"] = por[columnas_id].astype(str).agg("_".join, axis=1)

estudiantes_comunes = set(mat["student_key"]).intersection(
    set(por["student_key"])
)

print("Estudiantes identificados en ambas bases:",
      len(estudiantes_comunes))

estudiantes_comunes = set(mat["student_key"]).intersection(
    set(por["student_key"])
)

print("Estudiantes identificados en ambas bases:",
      len(estudiantes_comunes))

mat_unicos = mat.drop_duplicates("student_key")
por_unicos = por.drop_duplicates("student_key")

cruce = pd.merge(
    mat_unicos,
    por_unicos,
    on="student_key",
    suffixes=("_mat", "_por"),
    how="inner"
)

print("Tamaño de la base cruzada:")
print(cruce.shape)

print("Tamaño de la base cruzada:")
print(cruce.shape)

cruce.head()

comparacion_notas = cruce[
    ["G3_mat", "G3_por"]
]

print(comparacion_notas.head())

comparacion_notas = cruce[
    ["G3_mat", "G3_por"]
]

print(comparacion_notas.head())

cruce["diferencia_G3"] = (
    cruce["G3_mat"] - cruce["G3_por"]
)

print(cruce["diferencia_G3"].describe())

cruce["bajo_rendimiento_mat"] = (
    cruce["G3_mat"] < 10
).astype(int)

cruce["bajo_rendimiento_por"] = (
    cruce["G3_por"] < 10
).astype(int)

cruce["bajo_rendimiento_mat"] = (
    cruce["G3_mat"] < 10
).astype(int)

cruce["bajo_rendimiento_por"] = (
    cruce["G3_por"] < 10
).astype(int)

import matplotlib.pyplot as plt

promedios = [
    cruce["G3_mat"].mean(),
    cruce["G3_por"].mean()
]

plt.bar(
    ["Matemáticas", "Portugués"],
    promedios
)

plt.title("Comparación del rendimiento académico")
plt.ylabel("Promedio G3")
plt.show()

print(
    cruce[
        [
            "studytime_mat",
            "failures_mat",
            "absences_mat",
            "G3_mat"
        ]
    ].corr()
)